"""empty message

Revision ID: 20be49a69771
Revises: abaaf617224f
Create Date: 2023-09-16 18:45:31.393481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20be49a69771'
down_revision = 'abaaf617224f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cor1', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('cor2', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('cor3', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('cor4', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('cor5', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('cor6', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('cor7', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('cor8', sa.String(), nullable=False))
        batch_op.drop_column('marked_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marked_url', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('cor8')
        batch_op.drop_column('cor7')
        batch_op.drop_column('cor6')
        batch_op.drop_column('cor5')
        batch_op.drop_column('cor4')
        batch_op.drop_column('cor3')
        batch_op.drop_column('cor2')
        batch_op.drop_column('cor1')

    # ### end Alembic commands ###
